openapi: 3.0.1
info:
  title: Playground
  contact: {}
paths:
  /swagger:
    get:
      operationId: get
      responses:
        default:
          description: default response
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/SwaggerView'
  /v1/empty:
    get:
      operationId: get_1
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
  /index.html:
    get:
      operationId: indexPage
      parameters:
      - name: fullName
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/HelloWorldView'
  /hello-world:
    get:
      description: say hello and insert people to DB using myDao (interface)
      operationId: sayHello
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Saying'
    put:
      description: Blocking for certain period, block by sleep or block by postgres
      operationId: blocking
      parameters:
      - name: ms
        in: query
        schema:
          type: integer
          format: int64
      - name: pg
        in: query
        schema:
          type: boolean
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Saying'
  /hello-world/trace:
    get:
      operationId: sayTracing
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    SwaggerOAuth2Configuration:
      type: object
      properties:
        clientId:
          type: string
        clientSecret:
          type: string
        realm:
          type: string
        appName:
          type: string
        scopeSeparator:
          type: string
        additionalQueryStringParams:
          type: object
          additionalProperties:
            type: string
    SwaggerView:
      type: object
      properties:
        swaggerAssetsPath:
          type: string
        contextPath:
          type: string
        oauth2Configuration:
          $ref: '#/components/schemas/SwaggerOAuth2Configuration'
        showAuth:
          type: boolean
        showApiSelector:
          type: boolean
        validatorUrl:
          type: string
        title:
          type: string
    HelloWorldView:
      type: object
      properties:
        people:
          $ref: '#/components/schemas/People'
    People:
      type: object
      properties:
        fullName:
          type: string
        jobTitle:
          type: string
    Saying:
      type: object
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
